/**
 * Subtitle Formatter
 * 
 * Generates subtitles in various formats
 * Reference: subtitle-composing srt.py
 */

import { logger } from '../../../videocrew/src/core/logger.js';
import { existsSync, writeFileSync, mkdirSync } from 'fs';

/**
 * SubtitleFormatter Class
 */
export class SubtitleFormatter {
  constructor(options = {}) {
    this.name = 'SubtitleFormatter';
  }

  /**
   * Format segments to subtitle string
   */
  format(segments, format = 'srt') {
    logger.agent(this.name, `Formatting ${segments.length} segments to ${format}`);
    
    switch (format.toLowerCase()) {
      case 'vtt':
        return this.toVTT(segments);
      case 'ass':
        return this.toASS(segments);
      case 'srt':
      default:
        return this.toSRT(segments);
    }
  }

  /**
   * Format to SRT
   */
  toSRT(segments) {
    const lines = [];
    
    segments.forEach((seg, i) => {
      const start = this.formatTime(seg.start, 'srt');
      const end = this.formatTime(seg.end, 'srt');
      const text = seg.text || '';
      
      lines.push(`${i + 1}`);
      lines.push(`${start} --> ${end}`);
      lines.push(text);
      lines.push('');
    });
    
    return lines.join('\n');
  }

  /**
   * Format to WebVTT
   */
  toVTT(segments) {
    const lines = ['WEBVTT', ''];
    
    // Add metadata
    lines.push('NOTE Generated by VideoCrew');
    lines.push('');
    
    segments.forEach((seg, i) => {
      const start = this.formatTime(seg.start, 'vtt');
      const end = this.formatTime(seg.end, 'vtt');
      const text = seg.text || '';
      
      lines.push(`${i + 1}`);
      lines.push(`${start} --> ${end}`);
      lines.push(text);
      lines.push('');
    });
    
    return lines.join('\n');
  }

  /**
   * Format to ASS/SSA
   */
  toASS(segments) {
    const lines = [
      '[Script Info]',
      'Title: Generated Subtitles',
      'ScriptType: v4.00',
      '',
      '[V4+ Styles]',
      'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
      'Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1',
      '',
      '[Events]',
      'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
    ];
    
    segments.forEach((seg, i) => {
      const start = this.formatTime(seg.start, 'ass');
      const end = this.formatTime(seg.end, 'ass');
      const text = (seg.text || '').replace(/\n/g, '\\N');
      
      lines.push(`Dialogue: 0,${start},${end},Default,,0,0,0,,${text}`);
    });
    
    return lines.join('\n');
  }

  /**
   * Format time for SRT (HH:MM:SS,mmm)
   */
  formatTime(seconds, format = 'srt') {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.round((seconds % 1) * 1000);
    
    if (format === 'srt') {
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
    } else if (format === 'vtt') {
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(ms).padStart(3, '0')}`;
    } else if (format === 'ass') {
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(Math.floor(ms / 10).padStart(2, '0')}`;
    }
    
    return '00:00:00,000';
  }

  /**
   * Save subtitle to file
   */
  save(content, outputPath) {
    logger.agent(this.name, `Saving subtitle to ${outputPath}`);
    
    // Ensure directory exists
    const dir = outputPath.substring(0, outputPath.lastIndexOf('/'));
    if (dir && !existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    writeFileSync(outputPath, content, 'utf-8');
  }

  /**
   * Load subtitle from file
   */
  load(inputPath) {
    logger.agent(this.name, `Loading subtitle from ${inputPath}`);
    
    // TODO: Parse SRT/VTT/ASS file
    
    return [];
  }
}

export default SubtitleFormatter;
